### ISSUE TITLE
Getting and error when trying to build as a separate project

### ISSUE THREAD

**Issue by wpitallo** [retejs/vue-render-plugin#8]
HI, hope you can help.

 I am trying to build this project but get the following error after cloning and building after npm i:

$ npm run build

> rete-vue-render-plugin@0.3.3 build C:\_git\vue-render-plugin
> rete --build rete.config.js

Error when using sourcemap for reporting an error: Can't resolve original location of error.
(node:6484) UnhandledPromiseRejectionWarning: Error: 'default' is not exported by node_modules\vue-runtime-helpers\dist\normalize-component.js
    at error (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:3356:15)
    at Module.error (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:13140:9)
    at handleMissingExport (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:12612:21)
    at Module.traceVariable (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:13246:17)
    at ModuleScope.findVariable (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:12404:29)
    at Identifier$$1.bind (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:9586:40)
    at CallExpression.NodeBase.bind (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:9106:23)
    at CallExpression.bind (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:10162:31)
    at ExportDefaultDeclaration$$1.NodeBase.bind (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:9106:23)
    at ExportDefaultDeclaration$$1.bind (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:9760:31)
    at Program.NodeBase.bind (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:9102:31)
    at Module.bindReferences (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:13094:18)
    at Graph.link (C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:20738:20)
    at C:\_git\vue-render-plugin\node_modules\rollup\dist\rollup.js:20833:19
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
(node:6484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
handled with .catch(). (rejection id: 1)
(node:6484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wpitallo** [comment]
Added a fix for this in PR: https://github.com/retejs/vue-render-plugin/pull/7
as per: https://stackoverflow.com/questions/54379726/rollup-plugin-vue-v4-6-2-has-a-problem-with-vue-runtime-helpers
